export const SCRIPT = [
  ["red", "import "],
  ["white", "Developer "],
  ["red", "from "],
  ["white", '"'],
  ["yellow", "./Developer"],
  ["white", '";\n\n'],
  ["blue", "class OmarMoquete "],
  ["red", "extends "],
  ["yellow", "Developer "],
  ["white", "{ \n"],
  ["blue", "\n  constructor"],
  ["white", "() {\n\n"],
  ["gray", "    this."],
  ["white", "fullName "],
  ["red", "= new "],
  ["green", "Date"],
  ["white", "()."],
  ["green", "getFullyear"],
  ["white", "()"],
  ["red", " = "],
  ["purple", "1992"],
  ["white", ";\n\n"],
  ["gray", "    this."],
  ["white", "favSkill"],
  ["red", " = "],
  ["white", "{ \n"],
  ["white", "      teamOriented: "],
  ["purple", "10"],
  ["white", ";\n"],
  ["white", "      determination: "],
  ["purple", "10"],
  ["white", "; \n"],
  ["white", "      persistance: "],
  ["purple", "10"],
  ["white", ";\n"],
  ["white", "    };\n\n"],
  ["gray", "    this."],
  ["white", "hasPassion"],
  ["red", " = "],
  ["purple", "true"],
  ["white", ";\n\n"],
  ["white", "    }\n\n"],
  ["green", "    code"],
  ["orange", "(hrs) "],
  ["white", "{...\n"],
  ["white", "    }\n"],
  ["green", "    drinkCoffee"],
  ["orange", "(cups) "],
  ["white", "{...\n"],
  ["white", "    }\n\n"],
  ["red", "export default "],
  ["green", "OmarMoquete"],
  ["red", "()"],
  ["white", ";"],
];

export const WRITING_SPEED_IN_MILLISECONDS = 90;
